name: state_container
description: Flutter widget for control different states.
version: 0.2.0
homepage: https://github.com/mrxten/state_container

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter