name: state_container
description: Flutter widget for control different states.
version: 0.0.3+3
homepage: https://github.com/mrxten/state_container

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.0.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: